default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: db-dev

test:
  <<: *default
  username: postgres
  database: db-test

production:
  <<: *default
  database: eventnxt
  username: eventnxt
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
